import type { ExpressionSpecification, StyleSpecification } from "maplibre-gl";
import { PALETTE as c } from "./palette";

// Geographic context stays quieter than project geometry. No POI or road shields.
export function createMapStyle(): StyleSpecification {
  const name: ExpressionSpecification = ["coalesce", ["get", "name:en"], ["get", "name_en"], ["get", "name"]];
  return {
    version: 8,
    projection: { type: "globe" },
    glyphs: "https://tiles.openfreemap.org/fonts/{fontstack}/{range}.pbf",
    sky: {
      "atmosphere-blend": ["interpolate", ["linear"], ["zoom"], 0, 1, 5, 0.8, 8, 0],
      "sky-color": c["ink-0"], "horizon-color": c["map-horizon"], "fog-color": c["ink-0"],
      "sky-horizon-blend": 0.6, "horizon-fog-blend": 0.5, "fog-ground-blend": 0.2,
    },
    sources: {
      geography: { type: "vector", url: "https://tiles.openfreemap.org/planet" },
      sat: {
        type: "raster", tileSize: 256, maxzoom: 18,
        tiles: ["https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}"],
        attribution: "Imagery © Esri, Maxar, Earthstar Geographics",
      },
    },
    layers: [
      { id: "bg", type: "background", paint: { "background-color": c["map-land"] } },
      { id: "terrain-landcover", type: "fill", source: "geography", "source-layer": "landcover",
        paint: { "fill-color": ["match", ["get", "class"], "wood", c["map-forest"], "grass", c["map-grass"], "wetland", c["map-forest"], c["map-land"]], "fill-opacity": 0.85 } },
      { id: "terrain-urban", type: "fill", source: "geography", "source-layer": "landuse", minzoom: 6,
        filter: ["match", ["get", "class"], ["residential", "commercial", "industrial"], true, false],
        paint: { "fill-color": c["map-urban"], "fill-opacity": 0.55 } },
      { id: "terrain-parks", type: "fill", source: "geography", "source-layer": "park", minzoom: 5,
        paint: { "fill-color": c["map-park"], "fill-opacity": 0.5 } },
      { id: "terrain-water", type: "fill", source: "geography", "source-layer": "water",
        filter: ["!=", ["get", "brunnel"], "tunnel"], paint: { "fill-color": c["map-water"] } },
      { id: "terrain-water-edge", type: "line", source: "geography", "source-layer": "water", minzoom: 6,
        filter: ["!=", ["get", "brunnel"], "tunnel"], paint: { "line-color": c["map-water-edge"], "line-width": 0.7, "line-opacity": 0.65 } },
      { id: "terrain-rivers", type: "line", source: "geography", "source-layer": "waterway", minzoom: 6,
        filter: ["all", ["==", ["get", "class"], "river"], ["!=", ["get", "brunnel"], "tunnel"]],
        paint: { "line-color": c["map-river"], "line-width": ["interpolate", ["linear"], ["zoom"], 6, 0.7, 11, 2], "line-opacity": 0.65 } },
      { id: "terrain-roads-minor", type: "line", source: "geography", "source-layer": "transportation", minzoom: 10,
        filter: ["match", ["get", "class"], ["secondary", "tertiary", "minor", "street"], true, false],
        paint: { "line-color": c["map-road-minor"], "line-width": ["interpolate", ["linear"], ["zoom"], 10, 0.4, 14, 1.1], "line-opacity": 0.4 } },
      { id: "terrain-roads", type: "line", source: "geography", "source-layer": "transportation", minzoom: 5,
        filter: ["match", ["get", "class"], ["motorway", "trunk", "primary"], true, false],
        layout: { "line-cap": "round", "line-join": "round" },
        paint: { "line-color": c["map-road"], "line-width": ["interpolate", ["linear"], ["zoom"], 5, 0.5, 9, 1.1, 14, 2.5], "line-opacity": 0.55 } },
      { id: "terrain-boundaries", type: "line", source: "geography", "source-layer": "boundary", maxzoom: 7,
        filter: ["all", ["==", ["get", "admin_level"], 2], ["!=", ["get", "maritime"], 1]],
        paint: { "line-color": c["map-boundary"], "line-width": 0.7, "line-opacity": 0.45 } },
      { id: "sat", type: "raster", source: "sat", layout: { visibility: "none" },
        paint: { "raster-brightness-max": 0.65, "raster-saturation": -0.1 } },
      { id: "place-country", type: "symbol", source: "geography", "source-layer": "place", minzoom: 2, maxzoom: 5,
        filter: ["all", ["==", ["get", "class"], "country"], ["<=", ["get", "rank"], 2]],
        layout: { "text-field": name, "text-font": ["Noto Sans Regular"], "text-size": 13, "text-max-width": 8 },
        paint: { "text-color": c["map-label"], "text-halo-color": c["map-halo"], "text-halo-width": 1.5 } },
      { id: "place-state", type: "symbol", source: "geography", "source-layer": "place", minzoom: 4, maxzoom: 8,
        filter: ["==", ["get", "class"], "state"],
        layout: { "text-field": name, "text-font": ["Noto Sans Regular"], "text-size": 12, "text-letter-spacing": 0.12, "text-transform": "uppercase" },
        paint: { "text-color": c["map-label"], "text-halo-color": c["map-halo"], "text-halo-width": 1.5 } },
      { id: "place-city", type: "symbol", source: "geography", "source-layer": "place", minzoom: 5,
        filter: ["==", ["get", "class"], "city"],
        layout: { "text-field": name, "text-font": ["Noto Sans Regular"], "text-size": ["interpolate", ["linear"], ["zoom"], 5, 12, 10, 15], "text-padding": 12, "text-max-width": 9 },
        paint: { "text-color": c["map-label"], "text-halo-color": c["map-halo"], "text-halo-width": 1.8 } },
      { id: "place-town", type: "symbol", source: "geography", "source-layer": "place", minzoom: 8,
        filter: ["match", ["get", "class"], ["town", "village"], true, false],
        layout: { "text-field": name, "text-font": ["Noto Sans Regular"], "text-size": 12, "text-padding": 16, "text-max-width": 8 },
        paint: { "text-color": c["map-label"], "text-halo-color": c["map-halo"], "text-halo-width": 1.8 } },
      { id: "place-water", type: "symbol", source: "geography", "source-layer": "water_name", minzoom: 6,
        filter: ["==", ["geometry-type"], "Point"],
        layout: { "text-field": name, "text-font": ["Noto Sans Italic"], "text-size": 12, "text-padding": 20 },
        paint: { "text-color": c["map-water-label"], "text-halo-color": c["map-water"], "text-halo-width": 1.5 } },
    ],
  };
}
